### PR TITLE
Use Group.set() instead of assignment for Django 2.0 support

### PR DESCRIPTION
**Pull request by pintor**

### CODE REVIEW

**Comment by CCoffie** [comment]
Any idea when these changes might be merged? It would be helpful for those attempting to start Django projects with the latest version(v2.0+).

**Comment by fangli** [comment]
Hi this is really a good PR, I'm currently work on it.
BTW, since this module was used by many organizations and companies( including the one I'm working for), I have to keep the most backward compatibility. and it's a mission-critical module for most systems so I'll add some tests for different django versions.

Thanks all of you.

**Comment by CCoffie** [comment]
Hey @fangli, Don't mean to rush you or anything but would you happen to know when this will be deployed to pypi?

**Comment by ayr-ton** [comment]
@fangli I have the same question than @CCoffie

**Comment by bartek** [comment]
Would love to see a release as well! :)

**Comment by ayr-ton** [comment]
Just sent an e-mail to @fangli to confirm if he is following this thread.

**Comment by fangli** [comment]
Frankly speaking if you guys need a super well-maintained saml module I would like to recommand
https://github.com/onelogin/python-saml
to you, which released a few months ago.

I will keep maintaining this project but you know, the python-saml is supported by a company and, that's their bussiness.

Anyway, please feel free to use this one and thanks all of you.

**Pull request merged**
