### PR TITLE
Remove use of url `patterns` as it's removed in Django 1.10

### PR DESCRIPTION
**Pull request by jacobh**

### CODE REVIEW

**Comment by nbonnotte** [comment]
Looks great!

@fangli I hope this will be merged soon :)

**Comment by fangli** [comment]
Yes I hope we could move on to 1.10 right now but the fact is many old projects still use django 1.6-1.9, In order to keep backward-compatibility I did a lot to maintain the current code.

I will merge it soon and consider dropping the support for old django versions.

Thanks!

**Comment by hzy** [comment]
Django 1.6 (and possibly older versions) supports defining `urlpatterns` as a list - see http://django.readthedocs.io/en/1.6.x/topics/http/urls.html?highlight=urlpatterns#syntax-of-the-urlpatterns-variable

**Comment by FlipperPA** [comment]
Just revisiting this: the only currently supported versions of Django are now 1.8 (LTS) and 1.10.

Would it be worth making a branch for Django less than 1.7 and bringing the main branch and PyPI release up to 1.8 / 1.10 compatibility?

**Comment by willseward** [comment]
Whoops. I made a PR for this without looking first.

#15

**Pull request merged**
